/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fon.ai.np.mvnautoservisklijent.ui.view;

import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author Nikola
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTrenutniKorisnik = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuUsluge = new javax.swing.JMenu();
        jMenuItemDodajNovuUslugu = new javax.swing.JMenuItem();
        jMenuItemPretraziUsluge = new javax.swing.JMenuItem();
        jMenuItemIzmeniUslugu = new javax.swing.JMenuItem();
        jMenuItemIzbrisiUslugu = new javax.swing.JMenuItem();
        jMenuKlijenti = new javax.swing.JMenu();
        jMenuItemDodajKlijenta = new javax.swing.JMenuItem();
        jMenuItemPretraziKlijenta = new javax.swing.JMenuItem();
        jMenuItemIzmeniKlijenta = new javax.swing.JMenuItem();
        jMenuItemIzbrisiKlijenta = new javax.swing.JMenuItem();
        jMenuRacun = new javax.swing.JMenu();
        jMenuItemKreirajNovi = new javax.swing.JMenuItem();
        jMenuItemPretraziRacune = new javax.swing.JMenuItem();
        jMenuItemStornirajRacun = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Korisnik:");

        lblTrenutniKorisnik.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jMenuUsluge.setText("Usluge");

        jMenuItemDodajNovuUslugu.setText("Dodaj novu");
        jMenuUsluge.add(jMenuItemDodajNovuUslugu);

        jMenuItemPretraziUsluge.setText("Pretrazi");
        jMenuUsluge.add(jMenuItemPretraziUsluge);

        jMenuItemIzmeniUslugu.setText("Izmeni");
        jMenuUsluge.add(jMenuItemIzmeniUslugu);

        jMenuItemIzbrisiUslugu.setText("Obrisi");
        jMenuUsluge.add(jMenuItemIzbrisiUslugu);

        jMenuBar.add(jMenuUsluge);

        jMenuKlijenti.setText("Klijenti");

        jMenuItemDodajKlijenta.setText("Dodaj novog");
        jMenuKlijenti.add(jMenuItemDodajKlijenta);

        jMenuItemPretraziKlijenta.setText("Pretrazi");
        jMenuKlijenti.add(jMenuItemPretraziKlijenta);

        jMenuItemIzmeniKlijenta.setText("Izmeni");
        jMenuKlijenti.add(jMenuItemIzmeniKlijenta);

        jMenuItemIzbrisiKlijenta.setText("Obrisi");
        jMenuKlijenti.add(jMenuItemIzbrisiKlijenta);

        jMenuBar.add(jMenuKlijenti);

        jMenuRacun.setText(" Racuni");

        jMenuItemKreirajNovi.setText("Kreiraj novi");
        jMenuRacun.add(jMenuItemKreirajNovi);

        jMenuItemPretraziRacune.setText("Pretrazi");
        jMenuRacun.add(jMenuItemPretraziRacune);

        jMenuItemStornirajRacun.setText("Storniraj");
        jMenuRacun.add(jMenuItemStornirajRacun);

        jMenuBar.add(jMenuRacun);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTrenutniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(412, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTrenutniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(416, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemDodajKlijenta;
    private javax.swing.JMenuItem jMenuItemDodajNovuUslugu;
    private javax.swing.JMenuItem jMenuItemIzbrisiKlijenta;
    private javax.swing.JMenuItem jMenuItemIzbrisiUslugu;
    private javax.swing.JMenuItem jMenuItemIzmeniKlijenta;
    private javax.swing.JMenuItem jMenuItemIzmeniUslugu;
    private javax.swing.JMenuItem jMenuItemKreirajNovi;
    private javax.swing.JMenuItem jMenuItemPretraziKlijenta;
    private javax.swing.JMenuItem jMenuItemPretraziRacune;
    private javax.swing.JMenuItem jMenuItemPretraziUsluge;
    private javax.swing.JMenuItem jMenuItemStornirajRacun;
    private javax.swing.JMenu jMenuKlijenti;
    private javax.swing.JMenu jMenuRacun;
    private javax.swing.JMenu jMenuUsluge;
    private javax.swing.JLabel lblTrenutniKorisnik;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblTrenutniKorisnik() {
        return lblTrenutniKorisnik;
    }

    public JMenuItem getjMenuItemDodajKorisnika() {
        return jMenuItemDodajKlijenta;
    }

    public JMenuItem getjMenuItemDodajKlijenta() {
        return jMenuItemDodajKlijenta;
    }

    public JMenuItem getjMenuItemDodajNovuUslugu() {
        return jMenuItemDodajNovuUslugu;
    }

    public JMenuItem getjMenuItemIzbrisiKlijenta() {
        return jMenuItemIzbrisiKlijenta;
    }

    public JMenuItem getjMenuItemIzbrisiUslugu() {
        return jMenuItemIzbrisiUslugu;
    }

    public JMenuItem getjMenuItemIzmeniKlijenta() {
        return jMenuItemIzmeniKlijenta;
    }

    public JMenuItem getjMenuItemIzmeniUslugu() {
        return jMenuItemIzmeniUslugu;
    }

    public JMenuItem getjMenuItemKreirajNoviRacun() {
        return jMenuItemKreirajNovi;
    }

    public JMenuItem getjMenuItemPretraziKlijenta() {
        return jMenuItemPretraziKlijenta;
    }

    public JMenuItem getjMenuItemPretraziRacune() {
        return jMenuItemPretraziRacune;
    }

    public JMenuItem getjMenuItemPretraziUsluge() {
        return jMenuItemPretraziUsluge;
    }

    public JMenuItem getjMenuItemStornirajRacun() {
        return jMenuItemStornirajRacun;
    }

 

}
