/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fon.ai.np.mvnautoservisklijent.ui.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Nikola
 */
public class FRacun extends javax.swing.JDialog {

    /**
     * Creates new form FRacun
     */
    public FRacun(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKlijent = new javax.swing.JLabel();
        cmbKlijenti = new javax.swing.JComboBox<>();
        lblRacunID = new javax.swing.JLabel();
        txtRacunID = new javax.swing.JTextField();
        lblDatum = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtUkupnaVrednost = new javax.swing.JTextField();
        lblStorniran = new javax.swing.JLabel();
        checkStorniran = new javax.swing.JCheckBox();
        pnlStavkaRacuna = new javax.swing.JPanel();
        lblProizvod = new javax.swing.JLabel();
        cmbProizvod = new javax.swing.JComboBox<>();
        lblKolicina = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        lblVrednost = new javax.swing.JLabel();
        txtVrednostStavka = new javax.swing.JTextField();
        btnUnesi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        btnStornirajRacun = new javax.swing.JButton();
        pnlStavke = new javax.swing.JPanel();
        scrollPaneTblStavke = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnObrisiStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblKlijent.setText("Klijent:");

        lblRacunID.setText("RacunID:");

        txtRacunID.setEditable(false);
        txtRacunID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblDatum.setText("Datum:");

        txtDatum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumActionPerformed(evt);
            }
        });

        jLabel1.setText("Ukupna vrednost:");

        txtUkupnaVrednost.setEditable(false);
        txtUkupnaVrednost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblStorniran.setText("Storniran:");

        checkStorniran.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        checkStorniran.setEnabled(false);

        pnlStavkaRacuna.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavka Racuna"));

        lblProizvod.setText("Proizvod:");

        lblKolicina.setText("Kolicina:");

        txtKolicina.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtKolicina.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblVrednost.setText("Vrednost:");

        txtVrednostStavka.setEditable(false);
        txtVrednostStavka.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtVrednostStavka.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnUnesi.setText("Unesi");

        javax.swing.GroupLayout pnlStavkaRacunaLayout = new javax.swing.GroupLayout(pnlStavkaRacuna);
        pnlStavkaRacuna.setLayout(pnlStavkaRacunaLayout);
        pnlStavkaRacunaLayout.setHorizontalGroup(
            pnlStavkaRacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkaRacunaLayout.createSequentialGroup()
                .addGroup(pnlStavkaRacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStavkaRacunaLayout.createSequentialGroup()
                        .addGroup(pnlStavkaRacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKolicina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(pnlStavkaRacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbProizvod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKolicina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlStavkaRacunaLayout.createSequentialGroup()
                        .addComponent(lblVrednost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVrednostStavka, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStavkaRacunaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUnesi)))
                .addContainerGap())
        );
        pnlStavkaRacunaLayout.setVerticalGroup(
            pnlStavkaRacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkaRacunaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlStavkaRacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProizvod)
                    .addComponent(cmbProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStavkaRacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKolicina)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStavkaRacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVrednost)
                    .addComponent(txtVrednostStavka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUnesi))
        );

        btnSacuvaj.setText("Sacuvaj");

        btnOtkazi.setText("Otkazi");

        btnPonisti.setText("Ponisti");

        btnStornirajRacun.setText("Storniraj racun");

        scrollPaneTblStavke.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke racuna"));

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Redni broj", "Proizvod", "Vrednost", "Kolicina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneTblStavke.setViewportView(tblStavke);

        btnObrisiStavku.setText("Obrisi stavku");

        javax.swing.GroupLayout pnlStavkeLayout = new javax.swing.GroupLayout(pnlStavke);
        pnlStavke.setLayout(pnlStavkeLayout);
        pnlStavkeLayout.setHorizontalGroup(
            pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStavkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTblStavke, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStavkeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnObrisiStavku)
                .addGap(14, 14, 14))
        );
        pnlStavkeLayout.setVerticalGroup(
            pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTblStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisiStavku)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlStavkaRacuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStornirajRacun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(pnlStavke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStorniran, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRacunID, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRacunID)
                                    .addComponent(txtDatum)
                                    .addComponent(txtUkupnaVrednost, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkStorniran)
                                .addGap(86, 86, 86))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(cmbKlijenti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKlijent)
                    .addComponent(cmbKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRacunID)
                    .addComponent(txtRacunID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatum)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUkupnaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStorniran)
                    .addComponent(checkStorniran))
                .addGap(14, 14, 14)
                .addComponent(pnlStavke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStavkaRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnOtkazi)
                    .addComponent(btnPonisti)
                    .addComponent(btnStornirajRacun))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton btnStornirajRacun;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JCheckBox checkStorniran;
    private javax.swing.JComboBox<Object> cmbKlijenti;
    private javax.swing.JComboBox<Object> cmbProizvod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblKlijent;
    private javax.swing.JLabel lblKolicina;
    private javax.swing.JLabel lblProizvod;
    private javax.swing.JLabel lblRacunID;
    private javax.swing.JLabel lblStorniran;
    private javax.swing.JLabel lblVrednost;
    private javax.swing.JPanel pnlStavkaRacuna;
    private javax.swing.JPanel pnlStavke;
    private javax.swing.JScrollPane scrollPaneTblStavke;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtRacunID;
    private javax.swing.JTextField txtUkupnaVrednost;
    private javax.swing.JTextField txtVrednostStavka;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnOtkazi() {
        return btnOtkazi;
    }

    public JButton getBtnPonisti() {
        return btnPonisti;
    }

    public JButton getBtnSacuvaj() {
        return btnSacuvaj;
    }

    public JButton getBtnUnesi() {
        return btnUnesi;
    }

    public JCheckBox getCheckStorniran() {
        return checkStorniran;
    }

    public JComboBox<Object> getCmbKlijenti() {
        return cmbKlijenti;
    }

    public JComboBox<Object> getCmbProizvod() {
        return cmbProizvod;
    }

    public JLabel getLblRacunID() {
        return lblRacunID;
    }

    public JLabel getLblStorniran() {
        return lblStorniran;
    }

    public JPanel getPnlStavkaRacuna() {
        return pnlStavkaRacuna;
    }

    public JTextField getTxtKolicina() {
        return txtKolicina;
    }

    public JTextField getTxtRacunID() {
        return txtRacunID;
    }

    public JTextField getTxtUkupnaVrednost() {
        return txtUkupnaVrednost;
    }

    public JTextField getTxtVrednostStavke() {
        return txtVrednostStavka;
    }

    public JTextField getTxtDatum() {
        return txtDatum;
    }

    public JButton getBtnObrisiStavku() {
        return btnObrisiStavku;
    }

    public JButton getBtnStornirajRacun() {
        return btnStornirajRacun;
    }

    public JPanel getPnlStavke() {
        return pnlStavke;
    }

    public JScrollPane getScrollPaneTblStavke() {
        return scrollPaneTblStavke;
    }

    public JTable getTblStavke() {
        return tblStavke;
    }

}
